### ISSUE TITLE
feat: 메인화면 Body Component 작업

### ISSUE THREAD

**Issue by DevDAN09** [FUKUO-KA/soongsil-carries-love#15]
# ISSUE 🛠️ : 메인화면 Body 작업을 component 개발

## DESCRIPTION ✍🏻
메인화면 (Home) 에서 Body 컴포넌트화 작업할 예정입니다.

추가 사항 : 메인화면을 SPA형식으로 제공할 예정

예상되는 파일 구성
- Logo
- DashBoard
- FieChart
- BarChart

## Figma View 🖼️
<img width="278" alt="image" src="https://github.com/user-attachments/assets/38e1e886-f83b-482e-b475-735efcf35c17">

## TODO ✔️
- [ ] 메인화면 로고 추가
- [ ] 대시보드 컴포넌트 작업
- [ ] 통계 화면 컴포넌트 작업
## ETC

기타사항
