### ISSUE TITLE
feat: 통계화면 관련 API 연결 작업

### ISSUE THREAD

**Issue by DevDAN09** [FUKUO-KA/soongsil-carries-love#25]
# ISSUE 🛠️ : 통계화면 관련 API 연결 작업

## DESCRIPTION ✍🏻
- 통계화면에서 자신의 고등학교 동창의 성별, 학번 수를 알 수 있도록 합니다.

## TODO ✔️
- [x] user-count api 연결
- [x] student-count api 연결
- [x] gender-count api 연결
- [x] D3 패키지에서 해당 데이터를 연결

## ETC

기타사항
