### ISSUE TITLE
feat: 로그인/비로그인 별 홈 화면 설정

### ISSUE THREAD

**Issue by seocylucky** [FUKUO-KA/soongsil-carries-love#31]
# ISSUE 🛠️ : 로그인/비로그인 별 헤더 설정 및 스타일 수정

## DESCRIPTION ✍🏻

로그인/비로그인 별 헤더 설정 및 스타일 수정

로그인 시: navigation bar와 학교 정보(학교 이름이 길 경우, 스타일 어떻게 할건지 논의 필요) + 로그아웃 버튼 추가
비로그인 시: 로고 밑에 로그인 버튼

## Figma View 🖼️

| 비로그인 시 | 로그인 시 |
|:-----------:|:------------:|
|<img width="285" alt="image" src="https://github.com/user-attachments/assets/50c6c8c0-50bc-493a-8012-8848987c5f95">|<img width="285" alt="image" src="https://github.com/user-attachments/assets/88b0f09e-d451-4167-b92a-00013a7539c9">

## TODO ✔️

- [x] 로그인/비로그인 별 헤더 설정 및 스타일 수정
    - [x] 로그인 시, 학교 이름이 길 경우 처리
    - [x] 로그인 시, 로그아웃 버튼 추가
    - [x] 비로그인 시, 로고 밑에 로그인 버튼 추가
- [x] 홈화면 라우팅 `/home` => `/` 으로 변경

## ETC

기타사항
